name: Test
on:
  push:
    branches:
      - main
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Local Greet
        id  : greet
        uses: ./.github/actions/hello-docker
        with:
          who-to-greet: ワールド
      - name: Output time
        run: echo "${{ steps.greet.outputs.time }}"
      - name: Log exported variable
        run: echo $HELLO
      - name: Create issue
        id: issue
        uses: ./.github/actions/issue
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Title from WF
          body: Body from WF
          assignees: |
            fadhilahm
      - name: Print issue
        run: echo ${{ steps.issue.outputs.issue }}
