name: Issue
description: Action to create issue
author: fadhilahm
inputs:
  token:
    description: Github Token
    required: true
  title:
    description: Issue Title
    required: true
  body:
    description: Issue Body
    required: false
    default: Default Issue Body
  assignees:
    description: Issue Assignees
    required: true
outputs:
  issue: # id of output
    description: The issue object as a json string
runs:
  using: node16
  main: dist/index.js
